services:
  - type: web
    name: job-portal-laravel
    env: php
    plan: free
    buildCommand: |
      composer install
      php artisan migrate --force
      php artisan config:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
     
